### ISSUE TITLE
[Question] Enable on TeamSpeak ?

### ISSUE THREAD

**Issue by TheCalypso** [magneticflux-/fabric-mumblelink-mod#16]
Hello,
I have read your documentation which is very complete, however I am asking myself a question to which I still do not have the answer: Does the MumbleLink mod work for us TeamSpeak?

Thank you for your help ! And congratulations to you for this work ! 

- TheCalypso -

**Comment by magneticflux-** [comment]
I assume you mean the positional audio TeamSpeak supports through the CrossTalk addon? If so, it appears to already be supported! I didn't know, but apparently CrossTalk uses the Mumble specification for positional audio, which is fully supported by this mod.

https://github.com/thorwe/CrossTalk/wiki/Positional-Audio
> CrossTalk gets the positional information by implementing compatibility to the official Mumble 3D Positioning convention.

The only thing not supported is the automatic channel switching and server connecting, which is exclusive to Mumble right now. I do not know if TeamSpeak has a similar feature, but I will look into it to see if I could implement a toggle.

**Comment by TheCalypso** [comment]
Hello,
Yes, that's exactly what I meant! I did not quite understand the last part of your message. What do you mean by "the automatic channel switching and server connecting". Otherwise I can offer you my services if you need someone to test them! Do not hesitate to contact me ! Once again, congratulations to you for this work, congratulations!

- TheCalypso -

**Comment by magneticflux-** [comment]
Currently, the way Mumble Link automatically joins servers and server channels is by opening a special Mumble URI like `mumble://myserver.com/mychannel`. It appears as though TeamSpeak supports something similar [here](https://support.teamspeakusa.com/index.php?/Knowledgebase/Article/View/46/0/how-can-i-link-to-my-teamspeak-3-server-on-my-webpage).

This is needed because changing team or dimension in Minecraft should prevent you from hearing other people's voices (obviously configurable though).

I don't have a TeamSpeak setup, so I would appreciate any testing you can do. As far as I can tell, the basic positional audio functionality should work on both Mumble and TeamSpeak, but the channel-switching for different dimensions and teams only works on Mumble right now, and so should be disabled when using TeamSpeak.

**Comment by TheCalypso** [comment]
If you need to test do not hesitate to tell me what you want me to try, I will see if it is in my skills or just to test a mode build. However I had a question: I personally use the mod in 1.14.4 but if I use version 1.15.1 will it also work?

**Comment by magneticflux-** [comment]
I'm releasing a version that should work with TeamSpeak and allow channel switching and server joining to CurseForge now.

The mod itself might still work on 1.14.4, but some of the dependencies have been updated to 1.15.x so they would need to be manually downgraded to prevent it from crashing.

I'm not supporting versions older than the most recent because it would take too much effort to maintain each version separately. I can't justify the time spent since there are no donors to that feature and I'm not using this feature myself.

If you have any issues with the new TeamSpeak support, please file a new issue with the details!
