### ISSUE TITLE
Mumble works but not Teamspeak

### ISSUE THREAD

**Issue by bennyd87708** [magneticflux-/fabric-mumblelink-mod#79]
Hi, I'd like to get this to work for my TeamSpeak server, but it doesn't seem to do anything to the audio despite looking like it should be working. To test if something else was wrong, I set up a temporary Mumble server and managed to get it working perfectly there without any issues. I have a hunch that it could be because the player's coordinates aren't showing in Crosstalk as part of the collection of data being sent. I've attached screenshots of all the relevant TeamSpeak settings I can think of below (friends are using the exact same) and I am happy to test and troubleshoot anything to try to get this to work. Thanks so much!

![right pane](https://i.imgur.com/8O0cGdH.png)
![audio](https://i.imgur.com/drqY73Q.png)
![spread](https://i.imgur.com/chORfY5.png)

**Comment by bennyd87708** [comment]
If it might be of use, I also noticed that on other people, the little crosstalk details tab says "context: no match" even though we are standing right next to each other in-game.

![no match](https://i.imgur.com/GNYpDNe.png)

**Comment by magneticflux-** [comment]
What versions of the mod are you and your friend using?

**Comment by bennyd87708** [comment]
Fabric-Mumblelink-Mod-0.8.4

**Comment by magneticflux-** [comment]
Hmm...
Here is where the context is set:
https://github.com/magneticflux-/fabric-mumblelink-mod/blob/bc6bbb7391f824edc59f8962b973ad236afdd591/src/main/kotlin/com/skaggsm/mumblelinkmod/client/ClientMumbleLinkMod.kt#L162

And here is where the name is set:
https://github.com/magneticflux-/fabric-mumblelink-mod/blob/bc6bbb7391f824edc59f8962b973ad236afdd591/src/main/kotlin/com/skaggsm/mumblelinkmod/client/ClientMumbleLinkMod.kt#L154

They should always be the same if you're using the same mod and same version. I'll need to investigate how CrossTalk handles contexts to see if we're doing something it doesn't like. It seems pretty clear that this is a parity issue between CrossTalk and Mumble's handling of contexts.

**Comment by magneticflux-** [comment]
Stream-of-consciousness debugging:

At first I thought we might be forgetting to set the context length and Mumble just relies on a null terminator whereas CrossTalk relies on the length field, but that doesn't seem to be the case.

Us setting `context_len`:
https://github.com/magneticflux-/java-mumble-link/blob/4cb7c5b0d03d56cb1f5f2c3be92fd3cce012e3a4/src/main/java/com/skaggsm/jmumblelink/MumbleLinkImpl.java#L187

Mumble's handling of `context_len`:
https://github.com/mumble-voip/mumble/blob/b428cfc9f351ddb45efdcb9ce66ec552d656461e/plugins/link/link.cpp#L112

CrossTalk's handling of `context_len`:
https://github.com/thorwe/CrossTalk/blob/a89ef2eba482204862ef63a34afabf4b3dd34e36/src/positional_audio/shared_mem_reader.cpp#L160

---

Something else I noticed was that CrossTalk seems to be interpreting the data byte-wise, whereas Mumble interprets the data char-wise. This shouldn't be an issue since I don't know of any platforms where bytes and chars have difference sizes.

---

CrossTalk's use of `gsl::span` is just a fancy way to make a "view" or "slice" of an array, which it later copies to a vector. Everything seems correct there.

---

CrossTalk updates whether users share a context here:
https://github.com/thorwe/CrossTalk/blob/a89ef2eba482204862ef63a34afabf4b3dd34e36/src/positional_audio/mod_positionalaudio.cpp#L734-L748

One of those conditions must be failing for the message to be displayed. Maybe it's whatever `get_vr` is?

The value of `vr` is set here:
https://github.com/thorwe/CrossTalk/blob/a89ef2eba482204862ef63a34afabf4b3dd34e36/src/positional_audio/mod_positionalaudio.cpp#L694-L703

Which was read from a `QTextStream` created here:
https://github.com/thorwe/CrossTalk/blob/a89ef2eba482204862ef63a34afabf4b3dd34e36/src/positional_audio/mod_positionalaudio.cpp#L788-L796

If the context is empty (like in our case), it writes `"[Ct_None]"` to the stream.

When it's read back in by another client (I assume?) here:
https://github.com/thorwe/CrossTalk/blob/a89ef2eba482204862ef63a34afabf4b3dd34e36/src/positional_audio/mod_positionalaudio.cpp#L712-L722

It sets the context value to `"[Ct_None]"`, which is obviously not equal to `""`. I _think_ this is the root cause of the bug, and I'll report it to the developer of CrossTalk. Edit: reported here: https://github.com/thorwe/CrossTalk/issues/55

**Comment by bennyd87708** [comment]
Wow thanks for debugging so diligently! This might be a bit over my head, but hypothetically if the crosstalk developers are inactive for a while, do you think I could try to just throw an if statement in there checking for `"[Ct_None]"` to make it set the context value to `""` instead and then compile it myself or is it more complicated than that?

**Comment by magneticflux-** [comment]
Theoretically, I believe so.

It might be easier to compile a Java mod compared to a C++ project, though. You could recompile this mod for your friends and make the context some arbitrary, non-empty string. If you go down that route, just remember if anybody uses the mod without your modification they won't be able to hear you.

**Comment by bennyd87708** [comment]
Yep that did the trick!! Thanks so much for the help!
